version: "3"
services:
  node1:
    image: stellot/stellar-quickstart
    env_file: stellar-core.env
    command: "--privnet"
    ports:
      - 5432:5432
      - 9001:8000
    environment:
      - ARTIFICIALLY_GENERATE_LOAD_FOR_TESTING=true
      - ALLOW_LOCALHOST_FOR_TESTING=true
      - SELF=node1

  node2:
    image: stellot/stellar-quickstart
    env_file: stellar-core.env
    command: "--privnet"
    ports:
      - 9002:8000
    environment:
      - ARTIFICIALLY_GENERATE_LOAD_FOR_TESTING=true
      - ALLOW_LOCALHOST_FOR_TESTING=true
      - SELF=node2

  node3:
    image: stellot/stellar-quickstart
    env_file: stellar-core.env
    command: "--privnet"
    ports:
      - 9003:8000
    environment:
      - ARTIFICIALLY_GENERATE_LOAD_FOR_TESTING=true
      - ALLOW_LOCALHOST_FOR_TESTING=true
      - SELF=node3

  generator:
    build: 
      context: .
      dockerfile: ./cmd/generator/Dockerfile
    env_file: generator.env

  aggregator:
    build: 
      context: .
      dockerfile: ./cmd/aggregator/Dockerfile
    env_file: generator.env
