version: "3"
services:
  node1:
    image: stellot/stellar-quickstart
    env_file: stellar-core.env
    command: "--privnet"
    ports:
      - 9001:8000
    environment:
      - ARTIFICIALLY_GENERATE_LOAD_FOR_TESTING=true
      - ALLOW_LOCALHOST_FOR_TESTING=true
      - SELF=node1

  node2:
    image: stellot/stellar-quickstart
    env_file: stellar-core.env
    command: "--privnet"
    ports:
      - 9002:8000
    environment:
      - ARTIFICIALLY_GENERATE_LOAD_FOR_TESTING=true
      - ALLOW_LOCALHOST_FOR_TESTING=true
      - SELF=node2

  node3:
    image: stellot/stellar-quickstart
    env_file: stellar-core.env
    command: "--privnet"
    ports:
      - 9003:8000
    environment:
      - ARTIFICIALLY_GENERATE_LOAD_FOR_TESTING=true
      - ALLOW_LOCALHOST_FOR_TESTING=true
      - SELF=node3

  generator:
    build: generator-nodejs
    environment:
      - NETWORK_PASSPHRASE=Standalone Network ; February 2017
      - HORIZON_SERVER_URLS=http://node1:8000 http://node2:8000 http://node3:8000 
      - STELLAR_CORE_URLS=http://node1:11626 http://node2:11626 http://node3:11626
      - BATCH_SECRET_KEY=SCEXNGMD7TJF3KUYAEVI5MOVPQ7JIMXXVSSQEMB3EIIOJXGSQIIJJRSX
      - LOGS_NUMBER=20
      - PEROID=0
      - NO_DEVICES=500

