version: "3"
services:
  node1:
    image: stellot/stellar-quickstart
    env_file: stellar-core.env
    command: "--privnet"
    ports:
      - 9001:8000
    environment:
      - SELF=node1

  node2:
    image: stellot/stellar-quickstart
    env_file: stellar-core.env
    command: "--privnet"
    ports:
      - 9002:8000
    environment:
      - SELF=node2

  node3:
    image: stellot/stellar-quickstart
    env_file: stellar-core.env
    command: "--privnet"
    ports:
      - 9003:8000
    environment:
      - SELF=node3

  generator:
    build: .
    environment:
      - NETWORK_PASSPHRASE=Standalone Network ; February 2017
      - HORIZON_SERVER_URL=http://node1:8000
      - BATCH_SECRET_KEY=SCEXNGMD7TJF3KUYAEVI5MOVPQ7JIMXXVSSQEMB3EIIOJXGSQIIJJRSX
      - LOGS_NUMBER=10
      - PEROID=1000
      - NO_DEVICES=10

